# Generated by Django 3.0.5 on 2020-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='slug',
            field=models.SlugField(default='my way bitch'),
        ),
    ]
