# Generated by Django 3.0.5 on 2020-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_model1_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='slug',
            field=models.SlugField(default='hello'),
        ),
    ]
