# Generated by Django 3.0.5 on 2020-04-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200430_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model1',
            name='slug',
        ),
    ]
