# Generated by Django 3.0.5 on 2020-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_model1_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='slug',
            field=models.SlugField(default='on-my-way'),
            preserve_default=False,
        ),
    ]
