# Generated by Django 3.0.5 on 2020-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_model1_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
