# Generated by Django 3.0.5 on 2020-05-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200504_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model1',
            old_name='slug',
            new_name='name',
        ),
    ]
