# Generated by Django 3.0.5 on 2020-09-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200513_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model1',
            old_name='name',
            new_name='slug',
        ),
    ]
