# Generated by Django 3.0.5 on 2020-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200901_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='model1',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='model1',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
