# Generated by Django 3.0.5 on 2020-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20200905_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model1',
            options={'ordering': ['-pk', '-pub_date', '-updated', '-timestamp']},
        ),
    ]
