# Generated by Django 3.0.5 on 2020-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20200905_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
